# Setup script for cursor-otel-hook (Windows PowerShell)
# Run with: powershell -ExecutionPolicy Bypass -File setup.ps1

$ErrorActionPreference = "Stop"

# Save the project directory at the very beginning (use script location, not current directory)
$scriptPath = $PSScriptRoot
if ([string]::IsNullOrEmpty($scriptPath)) {
    # Fallback if $PSScriptRoot is not available (e.g., running in ISE)
    $scriptPath = Split-Path -Parent -Path $MyInvocation.MyCommand.Definition
}

$rawProjectPath = $scriptPath
if ($rawProjectPath -match '^Microsoft\.PowerShell\.Core\\FileSystem::(.+)$') {
    $projectDir = $matches[1]
} else {
    $projectDir = $rawProjectPath
}

Write-Host "=====================================" -ForegroundColor Cyan
Write-Host "Cursor OTEL Hook Setup (Windows)" -ForegroundColor Cyan
Write-Host "=====================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Project directory: $projectDir" -ForegroundColor Gray
Write-Host ""

# Check for Python
Write-Host "Checking for Python..." -NoNewline
try {
    $pythonVersion = & python --version 2>&1
    Write-Host " OK" -ForegroundColor Green
    Write-Host "  $pythonVersion" -ForegroundColor Gray
} catch {
    Write-Host " FAILED" -ForegroundColor Red
    Write-Host "Error: Python 3 is not installed or not in PATH" -ForegroundColor Red
    Write-Host "Please install Python 3.8 or higher from python.org"
    exit 1
}

# Create virtual environment if it doesn't exist
$venvPath = "$projectDir\venv"
if (!(Test-Path $venvPath)) {
    Write-Host ""
    Write-Host "Creating virtual environment..." -NoNewline
    python -m venv "$venvPath"
    Write-Host " OK" -ForegroundColor Green
} else {
    Write-Host ""
    Write-Host "Virtual environment already exists" -ForegroundColor Yellow
}

# Use venv python directly
$venvPython = "$venvPath\Scripts\python.exe"

# Upgrade pip
Write-Host ""
Write-Host "Upgrading pip..." -NoNewline
& $venvPython -m pip install --upgrade pip --quiet
Write-Host " OK" -ForegroundColor Green

# Install package
Write-Host ""
Write-Host "Installing pip packages for cursor-otel-hook..." -NoNewline
& $venvPython -m pip install -e "`"$projectDir`"" --quiet
Write-Host " OK" -ForegroundColor Green

# Create hooks directory
$cursorHooksDir = "$env:USERPROFILE\.cursor\hooks"
if (!(Test-Path $cursorHooksDir)) {
    Write-Host ""
    Write-Host "Creating Cursor hooks directory..." -NoNewline
    New-Item -ItemType Directory -Path $cursorHooksDir -Force | Out-Null
    Write-Host " OK" -ForegroundColor Green
    Write-Host "  Created $cursorHooksDir" -ForegroundColor Gray
}

# Create config file in Cursor profile directory
$configFile = "$cursorHooksDir\otel_config.json"
if (!(Test-Path $configFile)) {
    Write-Host ""
    Write-Host "Creating OTEL configuration file..." -NoNewline

    $configContent = @"
{
  "OTEL_EXPORTER_OTLP_ENDPOINT": "http://localhost:4317",
  "OTEL_SERVICE_NAME": "cursor-agent",
  "OTEL_EXPORTER_OTLP_PROTOCOL": "grpc",
  "OTEL_EXPORTER_OTLP_INSECURE": "true",
  "OTEL_EXPORTER_OTLP_HEADERS": null,
  "CURSOR_OTEL_MASK_PROMPTS": "false",
  "OTEL_EXPORTER_OTLP_TIMEOUT": "30"
}
"@

    Set-Content -Path $configFile -Value $configContent
    Write-Host " OK" -ForegroundColor Green
    Write-Host "  Created $configFile" -ForegroundColor Gray
} else {
    Write-Host ""
    Write-Host "Config already exists at $configFile" -ForegroundColor Yellow
}

# Create wrapper script
$wrapperScript = "$cursorHooksDir\otel_hook.bat"

Write-Host ""
Write-Host "Creating hook wrapper script..." -NoNewline

# Check if path is a UNC path (WSL or network)
$isUNCPath = $projectDir -match '^\\\\' -or $projectDir -match '^Microsoft\.PowerShell\.Core\\FileSystem::'

if ($isUNCPath) {
    # For UNC paths (like WSL), use WSL's bash to run the hook instead
    # Convert Windows config path to WSL path for the bash script
    $wslConfigPath = $configFile -replace '\\', '/' -replace '^([A-Z]):', '/mnt/$1' -replace '^/mnt/([A-Z])', { '/mnt/' + $_.Groups[1].Value.ToLower() }

    # Convert project path to WSL path
    $wslProjectPath = $projectDir -replace '\\\\wsl\.localhost\\Ubuntu-24\.04', '' -replace '\\', '/'

    $wrapperContent = @"
@echo off
REM Cursor OTEL Hook Wrapper
REM Auto-generated by setup.ps1

REM Run via WSL bash since project is in WSL
wsl.exe bash -c "cd '$wslProjectPath' && source venv/bin/activate && python -m cursor_otel_hook --config '$wslConfigPath'"
"@
} else {
    # For regular Windows paths, directly use the Python executable
    $wrapperContent = @"
@echo off
REM Cursor OTEL Hook Wrapper
REM Auto-generated by setup.ps1

REM Run the hook directly with venv Python
"$projectDir\venv\Scripts\python.exe" -m cursor_otel_hook --config "$configFile" %*
"@
}

Set-Content -Path $wrapperScript -Value $wrapperContent
Write-Host " OK" -ForegroundColor Green
Write-Host "  Created $wrapperScript" -ForegroundColor Gray

if ($isUNCPath) {
    Write-Host ""
    Write-Host "INFO: Project is on a UNC path (WSL/Network drive)" -ForegroundColor Yellow
    Write-Host "  Project path: $projectDir" -ForegroundColor Gray
    Write-Host "  Using WSL bash to run the hook" -ForegroundColor Gray
}

# Create hooks.json configuration
$hooksConfig = "$env:USERPROFILE\.cursor\hooks.json"
if (!(Test-Path $hooksConfig)) {
    Write-Host ""
    Write-Host "Creating hooks.json configuration..." -NoNewline

    # Escape backslashes for JSON
    $escapedWrapperScript = $wrapperScript -replace '\\', '\\'

    $hooksContent = @"
{
  "version": 1,
  "hooks": {
    "sessionStart": [
      {
        "command": "$escapedWrapperScript",
        "timeout": 5
      }
    ],
    "sessionEnd": [
      {
        "command": "$escapedWrapperScript",
        "timeout": 5
      }
    ],
    "postToolUse": [
      {
        "command": "$escapedWrapperScript",
        "timeout": 5
      }
    ],
    "afterShellExecution": [
      {
        "command": "$escapedWrapperScript",
        "timeout": 5
      }
    ],
    "afterMCPExecution": [
      {
        "command": "$escapedWrapperScript",
        "timeout": 5
      }
    ],
    "beforeReadFile": [
      {
        "command": "$escapedWrapperScript",
        "timeout": 5
      }
    ],
    "afterFileEdit": [
      {
        "command": "$escapedWrapperScript",
        "timeout": 5
      }
    ],
    "beforeSubmitPrompt": [
      {
        "command": "$escapedWrapperScript",
        "timeout": 5
      }
    ],
    "subagentStart": [
      {
        "command": "$escapedWrapperScript",
        "timeout": 5
      }
    ],
    "subagentStop": [
      {
        "command": "$escapedWrapperScript",
        "timeout": 5
      }
    ],
    "stop": [
      {
        "command": "$escapedWrapperScript",
        "timeout": 5
      }
    ]
  }
}
"@

    Set-Content -Path $hooksConfig -Value $hooksContent
    Write-Host " OK" -ForegroundColor Green
    Write-Host "  Created $hooksConfig" -ForegroundColor Gray
} else {
    Write-Host ""
    Write-Host "hooks.json already exists at $hooksConfig" -ForegroundColor Yellow
    Write-Host "  You may need to manually merge the configuration"
}

# Copy example HTTP config for reference
$exampleHttpConfig = "$projectDir\otel_config_http.example.json"
if (Test-Path "$projectDir\examples\otel_config_http.json") {
    Copy-Item "$projectDir\examples\otel_config_http.json" $exampleHttpConfig
    Write-Host ""
    Write-Host "Copied HTTP config example to $exampleHttpConfig" -ForegroundColor Green
}

Write-Host ""
Write-Host "=====================================" -ForegroundColor Green
Write-Host "Setup Complete!" -ForegroundColor Green
Write-Host "=====================================" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "1. Edit the configuration file to set your OTEL endpoint:"
Write-Host "   $configFile"
Write-Host ""
Write-Host "   The config uses standard OTEL environment variable names:"
Write-Host "   {"
Write-Host "     `"OTEL_EXPORTER_OTLP_ENDPOINT`": `"http://your-collector:4317`","
Write-Host "     `"OTEL_EXPORTER_OTLP_PROTOCOL`": `"grpc`","
Write-Host "     `"OTEL_EXPORTER_OTLP_HEADERS`": {`"authorization`": `"Bearer YOUR_TOKEN`"}"
Write-Host "   }"
Write-Host ""
Write-Host "2. Restart Cursor IDE to activate hooks"
Write-Host ""
Write-Host "Configuration files:" -ForegroundColor Cyan
Write-Host "  - Hooks: $hooksConfig"
Write-Host "  - OTEL Config: $configFile"
Write-Host "  - HTTP Example: $exampleHttpConfig"
Write-Host "  - Wrapper Script: $wrapperScript"
Write-Host ""
Write-Host "To test manually:"
Write-Host "  echo '{`"hook_event_name`":`"test`"}' | $wrapperScript"
Write-Host ""
Write-Host "To edit config:"
Write-Host "  notepad $configFile"
Write-Host "  # or: code $configFile, etc."
Write-Host ""
